### ISSUE TITLE
Modified Apk ? where to ?

### ISSUE THREAD

**Issue by jediafr** [getzze/gconnect#5]
I parsed the comments on reddit without finding anything related to a modified apk.
Maybe i missed it could you be kind enough to provide the link on your read me ?

**Comment by getzze** [comment]
Yeah, you need to build it yourself, they don't provide any upstream.
Check this comment for a pre-build modified apk:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/17#issuecomment-382967103
