### ISSUE TITLE
Error when running gconnectd

### ISSUE THREAD

**Issue by rodneyrod** [getzze/gconnect#8]
System is Arch Linux, x86_64

Followed build and installation steps listed in the readme, typing 'gconnectd' in the terminal results in this error:

gconnectd: error while loading shared libraries: libgconnect-0.1.so: cannot open shared object file: No such file or directory

**Comment by getzze** [comment]
Are you building from AUR?
If you are building the package yourself, it installs in `/usr/local` not `/usr`, therefore you need to specify to look for libraries in this root path. Try running:
```
LD_LIBRARY_PATH=/usr/local/lib/ GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0 gconnectd
```

EDIT: I added this information to the README

**Comment by rodneyrod** [comment]
Thanks I'll give that a shot, but would it be possible to have it symlink to /usr as well, or have sudo install put the objects in /usr, or is that not considered best practice?

**Comment by getzze** [comment]
In Arch, packages installed with pacman are installed in `/usr` and user-compiled apps are better fitted into `/usr/local` but this part is just a recommendation to keep your system clean:
https://superuser.com/questions/757269/where-to-install-programs-in-arch-linux

This being said, you can choose where to install the package with ninja:
https://mesonbuild.com/Installing.html#destdir-support

You can also install to `/usr/local` and add `/usr/local/include` to the library search path, but I didn't manage to add the GI path to the default search paths.

**Comment by rodneyrod** [comment]
So to make this work across reboots, I should add this line to my .bashrc file?

`LD_LIBRARY_PATH=/usr/local/lib/ GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0 gconnectd`
